#!/bin/bash
set -ex
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:$PATH
export LISTCAL="https://lists.hyperledger.org/ics/1902217/3131022486068381536/feed.ics"
cd /Users/ry/W/giocal
wget -q -O feed.ics $LISTCAL
python3 main.py | sort > parsed.txt

RC=`git diff HEAD parsed.txt | wc -l | awk '{print $1}'`
if [ "$RC" != "0" ]
then
  git add feed.ics parsed.txt
  git diff --compact-summary HEAD~ | git commit -a -s -F - 
  git push origin main
else
  echo No Updates.
fi
