#!/bin/bash
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
cd /Users/ry/W/giocal
/usr/local/bin/wget -q -O feed.ics https://lists.hyperledger.org/ics/1902217/3131022486068381536/feed.ics
/usr/local/bin/python3 main.py > parsed.txt

RC=`/usr/local/bin/git diff HEAD parsed.txt | /usr/bin/wc -l | /usr/bin/awk '{print $1}'`
if [ "$RC" != "0" ]
then
  /usr/local/bin/git add feed.ics parsed.txt
  /usr/local/bin/git commit -a -s -m "Update: $RC changes"
  /usr/local/bin/git push origin default
else
  echo No Updates.
fi
